repos:
  - repo: local
    hooks:
      - id: format-java
        name: Format Java Code (Spotless via Maven)
        entry: mvn spotless:apply
        language: system
        pass_filenames: false

      - id: test-java
        name: Run Java Tests
        entry: mvn test
        language: system
        pass_filenames: false